config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get 'sessions/new'

  get 'users/new'

	get "log_out" => "sessions#destroy", :as => "log_out"
	get "log_in" => "sessions#new", :as => "log_in"
	get "sign_up" => "users#new", :as => "sign_up"
  
	root :to => "users#index"

	resources :users do
		resources :contacts
	end
		
	resources :sessions

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :contacts
	accepts_nested_attributes_for :contacts

	has_secure_password

 	before_save { |user| user.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	helper_method :current_user

	private
	def current_user
		@current_user || User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    if current_user
      @contacts = current_user.contacts
      @contact = Contact.new
    else
      redirect_to '/log_in'
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    if current_user
      @contact = Contact.new(:user_id => current_user.id)
    else
      redirect_to '/log_in'
    end
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.js
    end
  end

      #format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      #format.json { head :no_content }

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone, :email, :address,:user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	
	end

	def create
		@user = User.find_by_email(params[:email])
		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to contacts_path
		else
			flash.now.alert = "Invalid email or password"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

	
	def new
 		@user = User.new
 	end

	def index
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to user_path(@user.id), :notice => "Signed up!"
		else
			render "new"
		end
	end

	private
	
	def user_params
		params.require(:user).permit(:email,:password,:password_confirmation)
	end

	def set_user
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_contact.html.erb
<% @contacts.each do |contact| %>
  <tr id="<%= contact.id %>">
		<td><%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, contact, method: :delete, remote: true %> 
    <%= link_to contact.name, contact %></td>
    <td><%= contact.phone %></td>
    <td><%= contact.email %></td>
    <td><%= contact.address %></td>
  </tr>
<% end %>

app/views/contacts/_contactTR.html.erb
  <tr id="<%= contact.id %>">
		<td><%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, contact, method: :delete, remote: true %> 
    <%= link_to contact.name, contact %></td>
    <td><%= contact.phone %></td>
    <td><%= contact.email %></td>
    <td><%= contact.address %></td>
  </tr>

app/views/contacts/_form.html.erb
<div class="container-fluid">
<%= form_for(@contact, remote: true) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/contacts/create.js.erb
$('tbody').append("<%= escape_javascript( render 'contactTR' )%>");
$('tr#<%= @contact.id %>').effect('highlight');

app/views/contacts/destroy.js.erb
$('#<%= @contact.id %>').fadeOut();

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= image_tag("icentrislogo.png") %> Address Book</h1>

<table id='contacts'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <%= render 'contact' %>
  </tbody>
</table>

<br>
<button data-toggle="collapse" data-target="#newContact">New Contact</button>

<div id="newContact" class="collapse well">
				<%= render 'form' %>
</div>

app/views/contacts/new.html.erb
<% if current_user %>
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ICentrisContacts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
				<%= yield %>

				<div class='container-fluid'>
								<div class='row'>
										<div id="user_nav" class='text-center'>
		<% if current_user %>
			Logged in as <%= current_user.email %>
			<%= link_to "Log out".html_safe, log_out_path %>
		<% else %>
						<%= link_to "<button type='button' class='btn btn-primary'>Sign up</button>".html_safe, sign_up_path %> or 
						<%= link_to "<button type='button' class='btn btn-default'>Log In</button>".html_safe, log_in_path %>
		<% end %>
	</div>
	</div>
	</div>

	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>

</body>
</html>

app/views/users/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class=" col-xs-12 well text-center">
						<%= image_tag("icentrislogo.png") %>			
			<h3>Addressbook</h1>
			<p>by Matt Cain</p>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
				<div class="row">
								<div class="col-xs-12 col-md-offset-5 col-md-3">
												<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form has errors</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
	<%= f.button "Sign me up", class: "btn btn-primary" %>
	</p>
<% end %>
</div>
</div>
</div>